In [2]:
# use numpy as backend, you can switch to torch if needed 
import numpy as np
import tensorly as tl
tl.set_backend('numpy')
from tensorly.testing import assert_array_equal

In [4]:
tensor = tl.tensor(np.arange(24).reshape((3, 4, 2)))
print('* original tensor:\n{}'.format(tensor))

* original tensor:
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [8]:
# unfold and fold operator

for mode in range(tensor.ndim):
    print('* mode-{} unfolding:\n{}'.format(mode, tl.unfold(tensor, mode)))

for mode in range(tensor.ndim):
    unfolding = tl.unfold(tensor, mode)
    folded = tl.fold(unfolding, mode, tensor.shape)
    
    # if not equal, will raise AssertionError 
    assert_array_equal(folded, tensor)
        

* mode-0 unfolding:
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
* mode-1 unfolding:
[[ 0  1  8  9 16 17]
 [ 2  3 10 11 18 19]
 [ 4  5 12 13 20 21]
 [ 6  7 14 15 22 23]]
* mode-2 unfolding:
[[ 0  2  4  6  8 10 12 14 16 18 20 22]
 [ 1  3  5  7  9 11 13 15 17 19 21 23]]


In [12]:
# tensor-2-vec and vector-2-tensor operator
tensor_2_vec = tl.tensor_to_vec(tensor)
print('* tensor to vector, result:\n{}'.format(tensor_2_vec))


vec_2_tensor = tl.vec_to_tensor(tensor_2_vec,tensor.shape)
print('*vector to tensor, result:\n{}'.format(vec_2_tensor))

* tensor to vector, result:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
*vector to tensor, result:
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
